services:
  # Next.js Application
  nxfs_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nxfs_frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./public:/app/public:ro
    networks:
      - main-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/api/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  main-network:
    driver: bridge
