version: '3.8'

services:
  # Next.js Application
  nxfs_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nxfs_frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=https://api.nxfs.no
      - NEXT_PUBLIC_N8N_WEBHOOK_URL=https://n8n.nxfs.no/webhook/nxfs
      - NEXT_PUBLIC_N8N_SECRET_KEY=${N8N_SECRET_KEY}
    volumes:
      - ./public:/app/public:ro
    networks:
      - nxfs-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional but recommended)
  nginx:
    image: nginx:alpine
    container_name: nxfs-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nxfs_frontend
    networks:
      - nxfs-network

  # Redis for caching (Optional)
  redis:
    image: redis:7-alpine
    container_name: nxfs-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - nxfs-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  nxfs-network:
    driver: bridge
